apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tsm-behandler
  namespace: tsm
  labels:
    team: tsm

spec:
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 30m
      memory: 512Mi
    limits:
      memory: 1Gi

  liveness:
    path: /internal/health/alive
  readiness:
    path: /internal/health/ready
  preStopHook:
    http:
      path: /internal/shutdown
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "nhn:hpr/export"
        - name: "nhn:flr/export"
  accessPolicy:
    inbound:
      rules:
        - application: syk-inn-api
        - application: syk-inn
        - application: zara
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: api.offentlig.test.hpr.nhn.no
  env:
    - name: HPR_EXPORT_ENDPOINT
      value: https://api.offentlig.test.hpr.nhn.no/v1/export
